CREATE TABLE `bili_nft_detail` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `item_id` BIGINT NOT NULL COMMENT '藏品系列ID',
  `item_name` VARCHAR(255) NOT NULL COMMENT '藏品系列名称',
  `issuer_name` VARCHAR(255) DEFAULT NULL COMMENT '发行方名称',
  `collection_total` INT DEFAULT NULL COMMENT '系列总数量',
  `is_private` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '系列是否私密',
  `serial_number` VARCHAR(32) DEFAULT NULL COMMENT '展示编号，例如 #11/3000',
  `serial_no` INT DEFAULT NULL COMMENT '编号序号，例如 11',
  `serial_total` INT DEFAULT NULL COMMENT '编号总量，例如 3000',
  `token_id` VARCHAR(64) DEFAULT NULL COMMENT 'token_id',
  `nft_id` VARCHAR(64) NOT NULL COMMENT 'NFT唯一标识',
  `nft_type` TINYINT DEFAULT NULL COMMENT 'NFT类型',
  `mid` BIGINT DEFAULT NULL COMMENT 'B站用户MID',
  `username` VARCHAR(128) DEFAULT NULL COMMENT '用户名，可能脱敏',
  `avatar_url` VARCHAR(512) DEFAULT NULL COMMENT '头像地址',
  `image_url` VARCHAR(512) DEFAULT NULL COMMENT '图片地址',
  `animation_url` VARCHAR(512) DEFAULT NULL COMMENT '动画地址',
  `crawl_time` DATETIME NOT NULL COMMENT '爬取时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_nft_id` (`nft_id`),
  UNIQUE KEY `uk_item_token_id` (`item_id`, `token_id`),
  KEY `idx_item_id` (`item_id`),
  KEY `idx_mid` (`mid`),
  KEY `idx_crawl_time` (`crawl_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='B站数字藏品明细表';

