CREATE TABLE `bili_nft_item_detail` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `item_id` BIGINT NOT NULL COMMENT '藏品系列ID',
  `nft_id` VARCHAR(64) NOT NULL COMMENT '藏品唯一ID',
  `nft_name` VARCHAR(255) NOT NULL COMMENT '藏品名称',
  `serial_number` VARCHAR(32) DEFAULT NULL COMMENT '展示编号，例如 #1/3000',
  `serial_no` INT DEFAULT NULL COMMENT '编号序号，例如 1',
  `serial_total` INT DEFAULT NULL COMMENT '编号总量，例如 3000',
  `nft_address` VARCHAR(255) DEFAULT NULL COMMENT '链上地址',
  `image_url` VARCHAR(512) DEFAULT NULL COMMENT '藏品图片地址',
  `animation_url` VARCHAR(512) DEFAULT NULL COMMENT '藏品动画地址',
  `html_url` VARCHAR(512) DEFAULT NULL COMMENT '藏品H5地址',
  `model_text` MEDIUMTEXT DEFAULT NULL COMMENT '3D模型原始文本',
  `owner_mid` BIGINT DEFAULT NULL COMMENT '持有人MID',
  `owner_name` VARCHAR(128) DEFAULT NULL COMMENT '持有人名称',
  `owner_avatar_url` VARCHAR(512) DEFAULT NULL COMMENT '持有人头像地址',
  `owner_tx_hash` VARCHAR(128) DEFAULT NULL COMMENT '持有人交易哈希',
  `owner_tx_time` DATE DEFAULT NULL COMMENT '持有交易时间',
  `owner_expire_time` VARCHAR(64) DEFAULT NULL COMMENT '持有过期时间',
  `issue_author` VARCHAR(255) DEFAULT NULL COMMENT '作者名称',
  `issue_issuer` VARCHAR(255) DEFAULT NULL COMMENT '发行方名称',
  `issue_time` DATE DEFAULT NULL COMMENT '发行时间',
  `issue_number` INT DEFAULT NULL COMMENT '发行总量',
  `description` TEXT DEFAULT NULL COMMENT '藏品描述',
  `attributes_json` JSON DEFAULT NULL COMMENT '属性列表JSON',
  `crawl_time` DATETIME NOT NULL COMMENT '爬取时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_nft_id` (`nft_id`),
  KEY `idx_item_id` (`item_id`),
  KEY `idx_owner_mid` (`owner_mid`),
  KEY `idx_issue_time` (`issue_time`),
  KEY `idx_crawl_time` (`crawl_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='B站数字藏品明细信息表';
